### ISSUE TITLE
Get VLAN setting from switchport, not only actual value

### ISSUE THREAD

**Issue by roeles** [germandutchwindtunnels/nettools#20]
Find out if it is possible to get the VLAN setting from all switchports, not just the current VLAN.
These differ in the case of dynamic VLANs with VMPS or RADUIS.

**Comment by roeles** [comment]
This is not possible in bulk. Performing the request on each port would cause too much load on the switches. Not going through with this.

**Comment by vermpat** [comment]
Isn't it possible to get the full configuration and just regex it out?

**Comment by roeles** [comment]
Possibly, but the current software has nothing to parse the configuration. This would mean a whole lot of trial/error to get to work.

**Comment by roeles** [comment]
A first version is underway, but this will make scripts **a lot** slower.
I'll include it into portconfig.py as a demo.
I would like to encourage @vermpat and @jaccovanschaik to do some testing an see if this is really what you want.

**Comment by roeles** [comment]
Commit aba27d01cef6081dedf78c85fb40ce7147e83363 has the new feature included in portconfig.py.
I'll leave implementation in a GUI up to @jaccovanschaik.
I'll include a separate table in the network_overview.py output. How to merge the two is shown in portconfig.py for @vermpat.
