### ISSUE TITLE
Remote span tool

### ISSUE THREAD

**Issue by roeles** [germandutchwindtunnels/nettools#22]
Build and test a commandline tool for setting up remote SPAN sessions.
Syntax:
`python remote_span.py username password source-switch source-port destination-switch destination-port`

When either source-port or destination-port is not given, show all options at the output.

**Comment by roeles** [comment]
@vermpat @jaccovanschaik: Which syntax would you prefer?
1. `python remote_span.py username password 1-10-2 10-3-1`
2. `python remote_span.py username password source-switch Gi1/0/1 dest-switch Gi3/0/18`

**Comment by vermpat** [comment]
I assume the first one would also need a source and a target switch right?
I still think the second one is better suited, for instance, what if we do
not have a patch-port setup on a specific switch port? With the first one
this would mean it is not possible to use that port.

2017-05-15 12:26 GMT+02:00 Roel Baardman <notifications@github.com>:

**Comment by roeles** [comment]
The first one would need no switches, since I can look that up in the same way as portconfig.py does.
If you prefer the second one, that's what I'll implement :-)

**Comment by vermpat** [comment]
yes please, i think that would be more useful, as i can see a lot of situations where we want to use a port on a switch that is not connected to a wallmount.

**Comment by roeles** [comment]
Solved by commit 609aba76ca284ccd2a74dd2a62f398deb259f5c1
