### ISSUE TITLE
Pyping considered annoying

### ISSUE THREAD

**Issue by jaccovanschaik** [germandutchwindtunnels/nettools#31]
There are a few problems with using the pyping module to test reachability of switches. First of all, it uses raw sockets, which means nettools must be run as root (on Linux) or Administrator (on Windows). This is annoying. Furthermore the pyping module is not included in a Python installation, so it must also be installed when installing nettools. This is an additional requirement that is easily forgotten. Finally, the benefit seems limited. There isn't all that much additional information to be learned from first testing reachability of a switch using pyping before actually trying to connect to it. For these reasons I propose to remove it.

**Comment by vermpat** [comment]
This has been done #32
