### ISSUE TITLE
Generate documentation from sourcecode

### ISSUE THREAD

**Issue by roeles** [germandutchwindtunnels/nettools#7]
Perhaps it makes sense to generate documentation from the docstrings in the python source.
Please weigh in if you have suggestions, @jaccovanschaik.

**Comment by jaccovanschaik** [comment]
I'm not a fan. It would be useless as user documentation, and if you want to know how the code works you can just open the source files and get the docstrings _and_ the accompanying code. It's all available and there's only a thousand lines or so. Extracting docstrings would be a waste of time, IMO.

**Comment by roeles** [comment]
Alright, thanks for your input. I agree.
